TestsEtValidations/CreditImmobilier/Controllers/MonthlyPaymentCalculationController.cs
using CreditImmobilier.Models.MonthlyPaymentCalculation;
using CreditImmobilier.Models.MonthlyPaymentCalculation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CreditImmobilier.Controllers
{
    public class MonthlyPaymentCalculationController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Title = "Calcul de mensualités";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calculation(MonthlyPaymentCalculationViewModel monthlyPaymentCalculationViewModel)
        {
            ViewBag.Title = "Résultat de simulation";

            Loan newLoan = new(monthlyPaymentCalculationViewModel.BorrowedCapital, monthlyPaymentCalculationViewModel.RateState, monthlyPaymentCalculationViewModel.RepaymentPeriodInMonths);
            Borrower newBorrower = new(monthlyPaymentCalculationViewModel.BorrowerIsAthletic, monthlyPaymentCalculationViewModel.BorrowerIsSmoker, monthlyPaymentCalculationViewModel.BorrowerHasHeartTrouble, monthlyPaymentCalculationViewModel.BorrowerIsComputerEngineer, monthlyPaymentCalculationViewModel.BorrowerIsFighterPilot);
            SimulationResult newSimulationResult = new(newLoan);
            Insurance newInsurance = new(newBorrower, newLoan);

            SimulationRecapViewModel simulationRecapViewModel = new(monthlyPaymentCalculationViewModel, newSimulationResult, newInsurance);

            return View("SimulationResult", simulationRecapViewModel);
        }

        
    }
}

TestsEtValidations/CreditImmobilier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tests Et Validations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tests Et Validations</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MonthlyPaymentCalculation" asp-action="Index">Calcul Mensualités</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Tests Et Validations - <a asp-area="" asp-controller="MonthlyPaymentCalculation" asp-action="Index">Calcul Mensualités</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>